### ISSUE TITLE
Перейти на кросс-платформенную библиотеку терминала

### ISSUE THREAD

**Issue by vladislav-atakhanov** [Harzu/rte#1]
Пока код не такой большой можно перейти на [crossterm](https://github.com/crossterm-rs/crossterm). Она работает как с Linux, так с Windows

**Comment by Harzu** [comment]
@vladislav-atakhanov 

Не до конца уверен в необходимости ) Этот репозиторий создан, как доп материал, для серии youtube роликов и он не особо претендует на серьезный и большой проект с долгой потдержкой. 

Если вдруг я передумаю, то это действительно ценный совет, и думаю отличное решение, благодарю за наводку.
